edition = "2021"
fn_single_line = false
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "One"
normalize_comments = true
normalize_doc_attributes = true
reorder_imports = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_try_shorthand = true
wrap_comments = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_modules = true
unstable_features = true
use_field_init_shorthand = true
