name: "Setup Rust"
description: "Setup the rust build environment"

inputs:
  version:
    description: "The version of Rust to use"
    required: true
    default: "1.65"
  profile:
    description: "The rustup profile to use"
    required: true
    default: "default"
  components:
    description: "Comma-separated list of the additional components to install, ex. clippy, rustfmt"
    required: false

outputs: {}

runs:
  using: composite

  steps:
    - name: "Install Rust ${{ inputs.version }}"
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.version }}
        profile: ${{ inputs.profile }}
        components: ${{ inputs.components }}
        override: true
