name: "AWS Login"
description: "Configure AWS Credentials"

inputs:
  aws-access-key-id:
    description: "The AWS access key ID"
    required: true
  aws-secret-access-key:
    description: "The AWS secret access key"
    required: true

outputs: {}

runs:
  using: composite

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-central-1
