version: '3.9'

services:
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--eval",
          "'db.runCommand(\"ping\").ok'",
          "localhost:27017/test",
          "--quiet"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=keyserver

  mongo-express:
    image: mongo-express
    ports:
      - 8085:8081
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL="mongodb://admin:admin@mongo:27017"