name: cd

on:
  workflow_dispatch:
    inputs:
      deploy_infra:
        description: "Whether to deploy infrastructure"
        default: true
        required: true
        type: boolean
      deploy_app:
        description: "Whether to deploy app"
        default: true
        required: true
        type: boolean
      deploy_prod:
        description: "Whether to deploy to production environment after sucessfull staging deployment"
        default: false
        required: true
        type: boolean
  workflow_call:
    inputs:
      deploy_infra:
        required: true
        type: boolean
      deploy_app:
        required: true
        type: boolean
      deploy_prod:
        required: true
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

concurrency: cd

env:
  IMAGE_NAME: "keyserver"

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.clean_version.outputs.version }}
    steps:
      - name: Get latest release for image version
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: draft

      - name: Get release value
        id: get_value
        uses: actions/github-script@v6
        env:
          LATEST_TAG: ${{ steps.latest_release.outputs.release }}
        with:
          result-encoding: string
          script: |
            if (context.eventName == "release") {
              return context.payload.release.tag_name
            } else {
              return process.env.LATEST_TAG
            }

      - name: Clean version
        id: clean_version
        run: |
          version=$(echo "${{ steps.get_value.outputs.result }}" | sed 's/v//g')
          echo "version=$version" >> $GITHUB_OUTPUT


  deploy-infra-staging:
    if: ${{ inputs.deploy_infra }}
    needs:
      - get-version
    uses: ./.github/workflows/deploy-infra.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      environment: 'staging'
      environment_url: https://staging.keys.walletconnect.com/health

  deploy-app-staging:
    if: ${{ inputs.deploy_app }}
    needs:
      - get-version
    uses: ./.github/workflows/deploy-app.yml
    secrets: inherit
    with:
      image_name: ${{ env.IMAGE_NAME }}
      version: ${{ needs.get-version.outputs.version }}
      environment: 'staging'
      environment_url: https://staging.keys.walletconnect.com/health

  validate:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [deploy-app-staging, deploy-infra-staging]
    runs-on: ubuntu-latest
    environment:
      name: app/staging
      url: https://staging.keys.walletconnect.com/health
    steps:
      - name: validate
        run: |
          curl "https://staging.keys.walletconnect.com/health"



  deployment_windows:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [validate]
    outputs:
      result: ${{ steps.decide.outputs.deploy_or_not }}
    runs-on: ubuntu-latest
    environment:
      name: app/prod
      url: https://keys.walletconnect.com/health
    steps:
      - id: decide
        uses: cobot/deploy-window-action@v1
        with:
          earliest-hour: "9"
          latest-hour: "17"
          latest-weekday: "5"
          time-zone: UTC
          force-deploy-phrase: force deploy

  deploy-infra-prod:
    # Only deploy if tests passed and deployment windows are open
    # Ignore deployment windows if workflow was started manually
    if: ${{ always() && inputs.deploy_infra && inputs.deploy_prod && needs.validate.result == 'success' && (needs.deployment_windows.outputs.result == 'yes' || github.event_name == 'workflow_dispatch') }}
    needs:
      - validate
      - deployment_windows
      - get-version
    uses: ./.github/workflows/deploy-infra.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      environment: 'prod'
      environment_url: https://keys.walletconnect.com/health

  deploy-app-prod:
    # Only deploy if tests passed and deployment windows are open
    # Ignore deployment windows if workflow was started manually
    if: ${{ always() && inputs.deploy_app && inputs.deploy_prod && needs.validate.result == 'success' && (needs.deployment_windows.outputs.result == 'yes' || github.event_name == 'workflow_dispatch') }}
    needs:
      - validate
      - deployment_windows
      - get-version
    uses: ./.github/workflows/deploy-app.yml
    secrets: inherit
    with:
      image_name: ${{ env.IMAGE_NAME }}
      version: ${{ needs.get-version.outputs.version }}
      environment: 'prod'
      environment_url: https://keys.walletconnect.com/health
