name: ci-infra

on:
  workflow_call:

concurrency: ci-infra

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Terraform data
        uses: actions/cache@v3
        with:
          path: terraform/.terraform
          key: ubuntu-latest-terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Init Terraform
        id: tf-init
        uses: WalletConnect/actions/terraform/init/@1.0.3
        with:
          environment: staging

      - name: Check Terraform Formatting
        id: tf-fmt
        uses: WalletConnect/actions/terraform/check-fmt/@1.0.3

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: aquasecurity/tfsec-action@v1.0.2
        with:
          working_directory: 'terraform'

  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache Terraform data
        uses: actions/cache@v3
        with:
          path: terraform/.terraform
          key: ubuntu-latest-terraform-${{ hashFiles('terraform/.terraform.lock.hcl') }}

      - name: Cache `tflint` plugins
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('terraform/.tflint.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Init Terraform
        id: tf-init
        uses: WalletConnect/actions/terraform/init/@1.0.3
        with:
          environment: staging

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.45.0

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        working-directory: 'terraform'

      - name: Check
        run: tflint --recursive --format=compact
        working-directory: 'terraform'

  staging:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/plan-infra.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      environment: 'staging'
      environment_url: https://staging.keys.walletconnect.com/health

  prod:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/plan-infra.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      environment: 'prod'
      environment_url: https://keys.walletconnect.com/health
