
name: ci

on:
  workflow_dispatch:
    inputs:
      infra:
        description: "Deploy infrastructure"
        default: true
        required: true
        type: boolean
      app:
        description: "Deploy app"
        default: true
        required: true
        type: boolean
      deploy:
        description: "Trigger deployment if CI is successful"
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - staging
          - prod
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
    

concurrency:
  # Support push/pr as event types with different behaviors each:
  # 1. push: queue up builds
  # 2. pr: only allow one run per PR
  group: ${{ github.workflow }}-${{ github.event.type }}${{ github.event.pull_request.number }}
  # If there is already a workflow running for the same pull request, cancel it
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      infra: ${{ steps.filter.outputs.infra }}
      app: ${{ steps.filter.outputs.app }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            infra:
              - 'terraform/**'
            app:
              - 'src/**'

  infra:
    needs: paths-filter
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.infra) || (github.event_name == 'pull_request' && needs.paths-filter.outputs.infra == 'true') }}
    uses: ./.github/workflows/ci-infra.yml
    secrets: inherit

  app:
    needs: paths-filter
    if: ${{ (github.event_name == 'workflow_dispatch' && inputs.app) || (github.event_name == 'pull_request' && needs.paths-filter.outputs.app == 'true') }}
    uses: ./.github/workflows/ci-app.yml
    secrets: inherit

  cd:
    needs:
      - infra
      - app
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') && ( github.event_name == 'release' || ( github.event_name == 'workflow_dispatch' && inputs.deploy != 'none' ) ) }}
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      deploy_infra: ${{ (github.event_name == 'workflow_dispatch' && inputs.infra) || (github.event_name == 'pull_request' && needs.paths-filter.outputs.infra == 'true') }}
      deploy_app: ${{ (github.event_name == 'workflow_dispatch' && inputs.app) || (github.event_name == 'pull_request' && needs.paths-filter.outputs.app == 'true') }}
      deploy_prod: ${{ github.event_name == 'release'  || (github.event_name == 'workflow_dispatch' && inputs.deploy == 'prod') }}
