name: ⚡ Push

on:
  push:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  aws:
    name: Login to AWS
    runs-on:
      group: ${{ vars.RUN_GROUP }}
    steps:
      - name: Configure AWS Credentials for Monitoring account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_MONITORING }}
          role-session-name: DebugAuthentication
          aws-region: ${{ vars.AWS_REGION }}
