name: Project Workflows

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check_pull_requests:
    name: Check linked issues
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
