name: ❖ CI

on:
  workflow_call:
    inputs:
      infra:
        description: 'Run Infrastructure CI'
        type: boolean
        default: true
      app:
        description: 'Run App CI'
        type: boolean
        default: true

permissions:
  id-token: write

jobs:
  check-infra:
    name: Infra CI
    uses: ./.github/workflows/sub-infra-check.yml
    if: ${{ inputs.infra }}
    secrets: inherit
    with:
      environment: 'wl-staging'

  check-app:
    name: App CI
    uses: ./.github/workflows/sub-app-check.yml
    if: ${{ inputs.app }}
    secrets: inherit

  plan-staging:
    name: Infra Plan Staging
    uses: ./.github/workflows/sub-infra-plan.yml
    needs: [check-infra]
    secrets: inherit
    with:
      version: 'latest'
      environment: 'wl-staging'
      environment-url: https://staging.${{ vars.SUBDOMAIN_NAME }}.walletconnect.com/health

  plan-prod:
    name: Infra Plan Prod
    uses: ./.github/workflows/sub-infra-plan.yml
    needs: [check-infra]
    secrets: inherit
    with:
      version: 'latest'
      environment: 'wl-prod'
      environment-url: https://${{ vars.SUBDOMAIN_NAME }}.walletconnect.com/health
